### ISSUE TITLE
Create Menu Design

### ISSUE THREAD

**Issue by DannyPeck** [cs-club-appdev/ac-menu#4]
We need to create a protocol / initial design for the menu system GUI.  Once we have a better idea of the menu system design we can begin designing the different pygame components to develop.

**Comment by trentspi** [comment]
Worked on the menu design at this weeks meeting. Did the bulk of the menu design @DannyPeck? Do we have any notes or pictures from the meeting?

**Comment by DannyPeck** [comment]
We sadly forgot to take notes or pictures from the meeting.  Our next step should be to document our design within the wiki.

**Comment by DannyPeck** [comment]
The Menu System has been through it's initial design phase.  Anything additional will be revisited in an iterative manner.
