### ISSUE TITLE
Replace default game icon with title text and random color background.

### ISSUE THREAD

**Issue by trentspi** [cs-club-appdev/ac-menu#46]
## Describe the current state:

As of right now, we use a default image (`default.png`) for games that do not have an `icon.png` in their directory.

## What should exist:

If an `icon.png` is not supplied, we should render the games metadata `title` over a random color background.

## How might this be implemented?:

- Remove the `default.png` implementation
- Access the games metadata to get the `title` value
- Choose a random color from an array of hex / rgb color values
- Render the random color and text as an icon using pygame, if there is no `icon.png` in a games' directory

## Why (be specific):

The current `default.png` is in use, but was merely placeholder for testing games... This implementation will be more descriptive for users to see the options of games they have to play.

## Other comments: 

This is a good beginner issue, if you have questions feel free to ask in slack or at the CS Club meetings! If you have contributed to the arcade cabinet already, consider allowing someone else to pick up this issue...

Here is an array of color values that may work well for our random color selection:
`["#0074D9", "#2ECC40", "#FFDC00", "#FF851B", "#FF4136", "#B10DC9", "#39CCCC", "#01FF70"]`

Source of colors I picked: https://clrs.cc/

Also, changing the title text color to be white or black based on the background color would be cool as well! For example, black text on blue is less favorable than white text, whereas black text on a light yellow is more favorable than white text.

**Comment by jaythras** [comment]
I'll tackle this.
