### ISSUE TITLE
Page indication on information page

### ISSUE THREAD

**Issue by trentspi** [cs-club-appdev/ac-menu#49]
## Describe the current state:

There is no way currently to know what page (of games) you are on or how many pages there are.

## What should exist:

We would like to add IOS-esque page indication circles with a highlighted circle to indicate the current page you are on.

## How might this be implemented?:

- Draw a black circle / ellipse element for each page in a row
- For the current page (get current page the user is on) draw a smaller white circle inside of the black circle representing that page.
- Draw the circles at the bottom of the information pane.

## Why (be specific):

This will allow users to see how many pages there are and which page they are currently on. The menu should open the first page on initial load, meaning the first circle would be highlighted.

**Comment by jake-white** [comment]
Done and merged into development.
